### ISSUE TITLE
[BUG 14] : Edge Browser ProtocolError: Protocol error is coming when the last browser is not closed

### ISSUE THREAD

**Issue by montbaga** [katalon-studio/Cloud-Studio#19]
**Is this something related to the chrome extension that we installed ?**
**Sometime it happens and sometimes it doesn't**
**not sure whether its website specific only**

**To Reproduce**
1. Run the test case and the respective browser will open
2. Don't close the browser window that is opened in step 1.
3. Run the test case again
4. Opening browser and Navigation to the url will throw a protocol error

**Expected behavior**
There should not be any error.

**Screenshots**
![image](https://github.com/katalon-studio/cloud-studio/assets/64852258/fb688c8a-0e77-42f2-83c0-220f2f523624)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser Edge and sometime on chrome

**Error Log**
Command Open the browser and navigate to 'https://testops.katalon.io' failed
**ProtocolError: Protocol error (Runtime.callFunctionOn): {"code":-32000,"message":"Cannot find context with specified id"}
at chrome-extension://elnoebihidlheoapfooeobbpmjgebpcj/background.js:120767:24**
at new Promise (<anonymous>)
at CDPSession.send (chrome-extension://elnoebihidlheoapfooeobbpmjgebpcj/background.js:120763:16)
at ExecutionContext._ExecutionContext_evaluate (chrome-extension://elnoebihidlheoapfooeobbpmjgebpcj/background.js:125162:46)
at ExecutionContext.evaluate (chrome-extension://elnoebihidlheoapfooeobbpmjgebpcj/background.js:125011:113)
at DOMWorld.evaluate (chrome-extension://elnoebihidlheoapfooeobbpmjgebpcj/background.js:121484:24)

**Comment by vyhuynhthanh** [comment]
Hi @montbaga
Thanks for logging this issue. We are investigating this and we'll let you know when it has been fixed.
